project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  sidebar:
    style: "docked"
    search: false
    contents:
      - href: index.qmd
        text: Home
      - 02-Lab-ObjectsInR/Lab2WriteUp.qmd
      - 03-Lab-ObjectsInR2/Lab3WriteUp.qmd
      - 04-Lab-Programming/Lab4WriteUp.qmd
      - 05-Lab-DataWrangling/Lab5WriteUp.qmd
      - 08-Lab-probability/Lab8WriteUp.qmd
      - 10-Lab-pointestimation/Lab10WriteUp.qmd
      - 11-Lab-Estimation/Lab11WriteUp.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto
