{
  "hash": "b23b693f11df039769189b2e4e837260",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab Ten -- Point Estimation # Title of the document\n\n# Bibliography Details\nbibliography: Lab10References.bib  # Name of bib file in the same folder \nbibliographystyle: apa            # Bibliography style\n\nexecute:               # Default settings for code blocks\n  warning: false       # Do not print warnings\n  message: false       # Do not print messages\n  size: \"scriptsize\"   # Set code size to script size\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"Lab10WriteUp.qmd\")\nformat:\n  pdf:        # Specify .pdf formatting options \n    documentclass: article     # Document Class\n    number-sections: true      # Number Sections\n    reference-section-title: \"References\" # Title for reference section\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables \n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n  html:       # Specify HTML formatting options \n    number-sections: true      # Number Sections\n    code-fold: true            # Button to show code\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables and figures\nformat-links: [pdf]\n---\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n\n\n**Tips**\n\n* Complete the tasks below. Make sure to start your solutions in on a new line that starts with \"**Solution**:\".\n* Make sure to use the Quarto Cheatsheet. This will make completing and writing up the lab *much* easier.\n* Make sure to use \"enter\" to make your code readable, so it doesn't run off the page. I switched the Quarto document to automatically render to .pdf, so you can see what you're submitting by default. You can switch back for the highlighting by moving the html block above the pdf block in the YAML header.\n* Don't forget that you can copy-and-paste code when you're doing something similar as we did in class!\n* Make sure to plot all computed probabilities. This is good `ggplot` practice AND will help make sure you don't make a mistake when computing the probability.\n\n\n# Lab 8 Notes\n\n##  Altham's Multiplicative Binomial Distribution\n\nThe PMF for Altham's Multiplicative Binomial Distribution is\n$$f_X(x) = \\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}I(x \\in \\{0, 1, ..., n\\})$$\nwhere\n$$c = \\sum_{i=0}^n {n \\choose i} p^i (1-p)^{n-i} \\theta^{i(n-i)}.$$ \nJust so we start on the same page, I have included my `R` function for computing probability using this distribution.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaltbinom <- function(x, size, prob, theta){\n  normalizing.constant <- 0\n  for(j in 0:size){\n    normalizing.constant <- normalizing.constant + \n      choose(size, j) * prob^j * (1-prob)^(size-j) * theta^(j*(size-j))\n  }\n  # Probability Mass at x=x\n  (1/normalizing.constant) *\n    choose(size, x) * prob^x * (1-prob)^(size-x) * theta^(x*(size-x)) *\n      (x>=0)*(x<=size)\n}\n```\n:::\n\n\n \\normalsize\n\n# Altham's Multiplicative Beta Binomial Distribution\nThe PMF for Altham's Multiplicative Beta Binomial Distribution is\n$$f_X(x) = \\left[\\int_{0}^1 \\left(\\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}\\right)\\left(\\frac{\\Gamma(\\alpha+\\beta)}{\\Gamma(\\alpha)\\Gamma(\\beta)} p^{\\alpha-1}(1-p)^{\\beta-1}\\right) dp\\right]I(x \\in \\{0, 1, ..., n\\})$$\n\nJust so we start on the same page, I have included my `R` function for computing probability using this distribution.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaltbbinom.single <- function(x, size, alpha, beta, theta){\n    integrand <- function(p) {\n    sapply(p, # integrate will pass in a vector, so we use sapply to apply the following\n           function(p_val){\n             # f(x|p) * f(p|alpha, beta)\n             daltbinom(x, size, p_val, theta) * dbeta(p_val, alpha, beta)\n           }\n    )\n  }\n  # Probability Mass at x=x\n  # integrate(integrand, lower = 0, upper = 1)$value * (x>=0)*(x<=size)\n  # I shrink the bounds below to avoid log(0)=-infinty\n  # I use try() to catch when there is an error and avoid crashing\n  res <- try(integrate(integrand, lower = 1e-7, upper = 1 - 1e-7)$value * \n                  (x>=0)*(x<=size), \n             silent = TRUE)\n  # If there is an error, return a near-zero probability\n  if(inherits(res, \"try-error\")) return(0.1^6)\n  \n  res\n}\n# Write a function that works on a vector\ndaltbbinom <- function(x, size, alpha, beta, theta){\n  sapply(X=x, FUN=daltbbinom.single, size=size, alpha=alpha, beta=beta, theta=theta)\n}\n```\n:::\n\n\n \\normalsize\n\n# Question 1\n\nIn Lab 8, we use Altham's Multiplicative Binomial Distribution. Your job was to interpret the impact of $\\theta$ in that equation. In this lab, we will model the number of legs won in a best of eleven (first to six) match. \n\nTo help us think about the interpretation, something that was challenging before, let's try something a little more manageable.\n\n## Part a\nSuppose a player has a 50\\% chance of winning a specific leg, that is let $p=0.50$. Let's look at the probability they win ($x=6$) legs in the match. Compute this probability over a sequence from $\\theta=0.5$ to $\\theta=1.5$ and plot it using a line where the $x$-axis is $\\theta$ and the $y$-axis is $P(X=6)$.\n\n**Solution**\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggdat <- tibble(theta = seq(0.5, 1.5, 0.001)) |>\n  mutate(Probability = daltbinom(6, size = 11, prob= 0.5, theta = theta))\n\nplot <- ggplot(ggdat) +\n  geom_line(aes(x = theta, y= Probability)) +\n  geom_hline(yintercept = 0) +\n  ylab(\"P(X=6)\") +\n  xlab(\"Theta\") +\n  theme_bw()\n\nplot\n```\n\n::: {.cell-output-display}\n![](Lab10WriteUp_files/figure-pdf/figure1-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n## Part b\nNow, plot Altham's Multiplicative Binomial Distribution under the same parameters with $\\theta=0.50$, $\\theta=1$, and $\\theta=1.5$. Use `ncol=1` in `facet_wrap()` to plot the PMFs in a single column for comparing.\n\n**Solution**\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggdat <- tibble(x = rep(seq(0, 11, 1),3), theta = c(rep(0.5, 12),rep(1,12),rep(1.5,12)))|>\n  mutate(PMF= daltbinom(x,11,0.5,theta))\n\nPMF.plot <- ggplot() +\n  geom_linerange(data = ggdat,\n                 aes(x = x, ymin = 0, ymax = PMF)) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks=0:11) +\n  scale_y_continuous(limits = c(0, 0.7)) +\n  ylab(\"Probability\") +\n  facet_wrap(~theta, ncol = 1) +\n  theme_bw()\n\nPMF.plot\n```\n\n::: {.cell-output-display}\n![](Lab10WriteUp_files/figure-pdf/figure2-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n## Part c\nWhat is your best assessment of what $\\theta$ is doing in this setting. Consider when a 6-0 blowout is most likely, and when a 5-6 nail-biter is most likely. Note here we should treat the match as a fixed $n=11$ as we did for $n=3$ in Lab 8.\\\n**Note:** In lab 8, we saw that small $\\theta$ meant wins came in bunches (clumped together), so there were more 2-0 wins in a best of three series.\n\n**Solution**\nWhen theta is greater, x, or the number of matches win, are likely to have higher probability at the center, which means wining 5 or 6 matches are more likely. This means when theta is lower, 6-0 is more likely and when theta is higher, 6-5 are more likely.\n\n# Question 2\n\n## Part a\nAltham's Multiplicative Binomial Distribution does not typically simplify to the clean $E(X)=np$ seen in the Binomial distribution, unless $\\theta = 1$. Write out the expression that would need to be solved to find $E(X^k)$, and then write a function that computes it given the proposed parameter values $p$ (`prob`) and $\\theta$ (`theta`).\n\n**Solution**\n\n$E(X^K) = \\sum_{i=0}^{11} i^k f_x(i)$\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmomdaltbinom <- function(p, theta, k){\n  x <- 0:11\n  sum(x^k*daltbinom(x,11,p,theta))\n}\n```\n:::\n\n\n \\normalsize\n\n## Part b\nDescribe how you can use your answer to part a to find Method of Moments estimates for the parameters $p$ and $\\theta$ for Altham's Multiplicative Binomial Distribution based on data.\n\n**Solution**\n\nWe can calculate the $\\bar{x}$ and set it equal to $\\sum_{i=0}^{11} x_i f_x(x_i)$; calculate $\\overline{x^2}$ and set it equal to $\\sum_{i=0}^{11} x_i ^2 f_x(x_i)$ and solve for p and theta.\n\n## Part c\nWrite a function that computes the log-likelihood for Altham's Multiplicative Binomial Distribution, given data (`x`) and proposed parameter values $p$ (`prob`) and $\\theta$ (`theta`).\n\n**Solution**\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlldaltbinom <- function(par, data, MLE = F){\n  p <- ifelse(MLE, 1/(1+exp(-par[1])), par[1])\n  theta <- ifelse(MLE, exp(par[2]), par[2])\n  ll <- sum(log(daltbinom(data,11,p,theta)))\n  ifelse(MLE, -ll, ll)\n}\n```\n:::\n\n\n \\normalsize\n\n## Part d\nDescribe how you can use your answer to part c to find Maximum Likelihood estimates for the parameters $p$ and $\\theta$ for Altham's Multiplicative Binomial Distribution based on data.\n\n**Solution**\n\nUse optim() to find the parameter that allows the log likelihood function to have the greatest value, and set MLE in the function equal to True.\n\n# Lab 10\nPeter \"Snakebite\" Wright is a two-time Professional Darts Corporation World Champion (2020, 2022) and a former World No. 1. He is one of the sport's most decorated players, winning nearly 50 PDC titles including the World Matchplay, UK Open, and multiple European Championships. \n\nIn 2024, he made The Premier League -- a league involving the eight best players that runs every Thursday night from February to May. In this season, he won two of eighteen matches, securing only four points. The spread in legs won was -43, meaning he lost 43 more legs than he won. This performance was rather quite bad. He was soundly trounced in almost all his match ups. \n\n\nThe 2024 standings are below:\n\n| Rank | Player             |\n|:-----|:-------------------|\n| 1    |Luke Littler        |\n| 2    |Luke Humphries      |\n| 3    |Michael van Gerwen  |\n| 4    |Michael Smith       |\n| 5    |Nathan Aspinall     |\n| 6    |Rob Cross           |\n| 7    |Gerwyn Price        |\n| 8    |Peter Wright        |\n\n\n## Summarize the 2024 Data\n\nIn `pdc2024.csv`, I have provided the data for the 2024 Premier League season. There are a few data cleaning steps to consider.\n\n  * Remove any matches with no `Score` (e.g., a bye or walkover)\n  * Nights 1 through 16 are best of 11 (first to 6), but the playoffs are extended. For consistency, keep nights 1 through 16 only.\n  * Make two columns `WinnerLegs` and `LoserLegs` that keep track of the number of legs each player has won\n  \nSummarize the data. What do the data tell us about the breakdown of the results?\n\n**Solution**\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.pdc <- read_csv(\"pdc2024.csv\")\n\ndat.pdc.clean <- dat.pdc |>\n  filter(Score != \"w/o\") |>\n  filter(Night != \"Finals\") |>\n  mutate(WinnerLegs = as.numeric(str_split(Score, \"-\", simplify = TRUE)[,1]),\n         LoserLegs  = as.numeric(str_split(Score, \"-\", simplify = TRUE)[,2]))\n```\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMatchwins <- function(name){\n  win <- 0\n  for(i in 1:nrow(dat.pdc.clean)){\n    if(dat.pdc.clean$Winner[i]==name){\n      win <- win + 1\n    }\n  }\n  win\n}\n\ntotal <- function(name){\n  total <- 0\n  for(i in 1:nrow(dat.pdc.clean)){\n    if(dat.pdc.clean$Winner[i]==name | dat.pdc.clean$Loser[i]==name){\n      total <- total + 1\n    }\n  }\n  total \n}\n\nlegwins <- function(name){\n  legwin <- 0\n  for(i in 1:nrow(dat.pdc.clean)){\n    if(dat.pdc.clean$Winner[i]==name){\n      legwin <- legwin + 6\n    }\n    else if(dat.pdc.clean$Loser[i]==name){\n      legwin <- legwin + dat.pdc.clean$LoserLegs[i]\n    }\n  }\n  legwin\n}\n\nlegtotal <- function(name){\n  total <- 0\n  for(i in 1:nrow(dat.pdc.clean)){\n    if(dat.pdc.clean$Winner[i]==name | dat.pdc.clean$Loser[i]==name){\n      total <- total + dat.pdc.clean$LoserLegs[i] + dat.pdc.clean$WinnerLegs[i]\n    }\n  }\n  total \n}\n\nplayer.turns <- table(c(dat.pdc.clean$Winner, dat.pdc.clean$Loser)) \nmatch.summary <- tibble(Name = names(player.turns),\n                  Match.Win = sapply(names(player.turns), Matchwins),\n                  Match.Total = sapply(names(player.turns), total)) |>\n                  mutate(Proportion = Match.Win / Match.Total)\n\nleg.summary <-  tibble(Name = names(player.turns),\n                       Leg.Win = sapply(names(player.turns), legwins),\n                       Leg.Total = sapply(names(player.turns), legtotal))  |>\n                mutate(Proportion = Leg.Win / Leg.Total)\n\nmatch.plot <- ggplot(data = match.summary) +\n  geom_bar(aes(x = Name, y = Proportion), stat = \"identity\") +\n  geom_hline(yintercept = 0) +\n  theme_bw() +\n  labs(x = \"Player Name\", y = \"Winning Matches Proportion\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10))\n\nleg.plot <- ggplot(data = leg.summary) +\n  geom_bar(aes(x = Name, y = Proportion), stat = \"identity\") +\n  geom_hline(yintercept = 0) +\n  theme_bw() +\n  labs(x = \"Player Name\", y = \"Winning Legs Proportion\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10))\n```\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell tbl-cap='Matches won by each player' tbl-align='center'}\n::: {.cell-output-display}\n\n\n|Name               | Match.Win| Match.Total| Proportion|\n|:------------------|---------:|-----------:|----------:|\n|Gerwyn Price       |         7|          22|       0.32|\n|Luke Humphries     |        20|          32|       0.62|\n|Luke Littler       |        24|          36|       0.67|\n|Michael Smith      |        17|          31|       0.55|\n|Michael van Gerwen |        16|          28|       0.57|\n|Nathan Aspinall    |        15|          29|       0.52|\n|Peter Wright       |         2|          18|       0.11|\n|Rob Cross          |        10|          26|       0.38|\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nmatch.plot\n```\n\n::: {.cell-output-display}\n![](Lab10WriteUp_files/figure-pdf/figure3-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell tbl-cap='Legs won by each player' tbl-align='center'}\n::: {.cell-output-display}\n\n\n|Name               | Leg.Win| Leg.Total| Proportion|\n|:------------------|-------:|---------:|----------:|\n|Gerwyn Price       |      95|       211|       0.45|\n|Luke Humphries     |     169|       301|       0.56|\n|Luke Littler       |     193|       348|       0.55|\n|Michael Smith      |     150|       300|       0.50|\n|Michael van Gerwen |     135|       270|       0.50|\n|Nathan Aspinall    |     143|       282|       0.51|\n|Peter Wright       |      61|       165|       0.37|\n|Rob Cross          |     115|       245|       0.47|\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nleg.plot\n```\n\n::: {.cell-output-display}\n![](Lab10WriteUp_files/figure-pdf/figure4-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nI use the data to calculate the total number of matches played by each player and the number of matches they won. I also compute their match winning proportions. The results show that Peter Wright has the lowest winning proportion, while Luke Littler has the highest.\n\nAdditionally, I calculate the total number of legs played by each player and the number of legs they won. There is less variation in leg winning proportions compared to match winning proportions. Although Peter Wright still has the lowest proportion, his leg winning proportion is a lot higher than his match winning proportion, but it is still lower than other players.\n\n\n## Altham's Multiplicative Binomial Distribution\nFor each player in the 2024 season, use the number of legs won in each match to compute maximium likelihood estimates for $p$ and $\\theta$. \\\n**Note**: The \"for each\" here can be done more efficiently with a function or a loop!\n\n* Create a vector containing the number of legs won by the player. Note sometimes you will need to pull from winner's legs and sometimes from the loser's legs.\n* Find the MLE for the player using this data. Ensure to report $p$ and $\\theta$ for each player in a nicely formatted table.\\\n**Note:** In Lecture on Monday, we used transformations to restrict how `optim()` searches the parameter space. For example, here, you might consider\n`p <- 1/(1+exp(-par[1]))` and `theta <- exp(par[2])`.\n* Make comments about the MLEs in the context of the standings.\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplayer.turns <- table(c(dat.pdc.clean$Winner, dat.pdc.clean$Loser)) \n\n# This function returns a data frame that contains two column. \n# First column is number of legs the player wins in each match, \n# and the second column is the total legs that the player played for each match.\nWin.each <- function(name){                      \n  total.turn <- as.numeric(player.turns[name])\n  win.each <- tibble(Win = rep(NA, total.turn),\n                    Total = rep(NA, total.turn))\n  n <- 1\n  for(i in 1:nrow(dat.pdc.clean)){\n    if(dat.pdc.clean$Winner[i]==name){ # If the player is the winner\n      win.each$Win[n] <- 6\n      win.each$Total[n] <- dat.pdc.clean$LoserLegs[i] + dat.pdc.clean$WinnerLegs[i]\n      n <- n + 1\n    }\n    else if(dat.pdc.clean$Loser[i]==name){ # If the player is the loser\n      win.each$Win[n] <- dat.pdc.clean$LoserLegs[i]\n      win.each$Total[n] <- dat.pdc.clean$LoserLegs[i] + dat.pdc.clean$WinnerLegs[i]\n      n <- n + 1 \n    }\n  }\n  win.each\n}\n\n# This function calculates the probability of the player \n# winning x time in n legs with given probability and theta. \n# If the player win the match, it ensures the last leg is a win, \n# If the player lose the match, it ensures the last leg is a lose.\n# Since player did not play 11 legs, size is also a vector that contains different total legs each player played.\n\nProb.daltbinom <- function(x, size, prob, theta){  \n  sapply(1:length(x), function(i){  # Ensure it works on a vector\n    xi <- x[i]  \n    si <- size[i]  \n    if(xi == 6){  # If the player win the match\n      # Calculate the probability and ensuring the last leg is win\n      (choose(si-1,5)/choose(si, xi)) * daltbinom(xi, si, prob, theta) \n    } else {  # If the player lose the match\n      # Calculate the probability and ensuring the last leg is lose\n      (choose(si-1, xi)/choose(si, xi)) * daltbinom(xi, si, prob, theta)  \n    }  \n  })  \n}\n\n# This function calculates the log likelihood of different parameters. \n# In order to make it easier for optimization, it returns the negative log likelihood.\nllProb.daltbinom <- function(par, data){\n  p <- 1/(1+exp(-par[1]))  # Ensures probability is between 0 and 1\n  theta <- exp(par[2])     # Ensures theta is greater than 0\n  x <- data$Win\n  size <- data$Total\n  ll <- sum(log(Prob.daltbinom(x,size,p,theta)))\n  -ll\n}\n\n# Create a summary table for the result\nMLE.summary <- tibble(Name = names(player.turns),\n                      P = NA,\n                      Theta = NA)\n\n# Repeat the process for each player\nfor(i in 1:nrow(MLE.summary)){\n  name <- MLE.summary$Name[i]\n  win.each <- Win.each(name) \n  mle <- optim(par = c(0,0), fn = llProb.daltbinom, \n             data = win.each)\n  MLE.summary$P[i] <- 1/(1+exp(-mle$par[1]))\n  MLE.summary$Theta[i] <- exp(mle$par[2])\n}\n```\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell tbl-cap='P and Theta for each player' tbl-align='center'}\n::: {.cell-output-display}\n\n\n|Name               |    P| Theta|\n|:------------------|----:|-----:|\n|Gerwyn Price       | 0.43|  1.12|\n|Luke Humphries     | 0.58|  1.08|\n|Luke Littler       | 0.59|  1.14|\n|Michael Smith      | 0.50|  1.11|\n|Michael van Gerwen | 0.50|  1.11|\n|Nathan Aspinall    | 0.51|  1.14|\n|Peter Wright       | 0.24|  1.30|\n|Rob Cross          | 0.46|  1.04|\n\n\n:::\n:::\n\n\n \\normalsize\n\nThe data represent the maximum likelihood of p and theta for each player. It means each player are most likely to have p probability of winning each match if their results follows Altham's Multiplicative Binomial Distribution. \n\n## Altham's Multiplicative Beta Binomial Distribution\n\nFor each player in the 2024 season, use the number of legs won in each match to compute maxmium likelihood estimates for $p$ and $\\theta$.\\\n**Note**: The \"for each\" here can be done more efficiently with a function or a loop!\n\n* Create a vector containing the number of legs won by the player. Note sometimes you will need to pull from winner's legs and sometimes from the loser's legs.\n* Find the MLEs for the player using this data. Ensure to report $\\alpha$, $\\beta$, and $\\theta$ for each player in a nicely formatted table.\\\n**Note 1**: Due to the computational complexity of `integrate()`, you should compute the logged probability for `0:6` once and add them according to the data in each player's vector.\n**Note 2**: In Lecture on Monday, we used transformations to restrict how `optim()` searches the parameter space.\n* Plot the underlying Beta($\\alpha$, $\\beta$) distribution for each player. \\\n**Note**: Add the mean and variance of the Beta to the table of MLEs. Recall\n\\begin{align*}\n E(X)   &= \\frac{\\alpha}{\\alpha+\\beta}\\\\\n sd(X) &= \\sqrt{\\frac{\\alpha\\beta}{(\\alpha+\\beta)^2(\\alpha+\\beta+1)}}\n\\end{align*}\n* Make comments about the MLEs in the context of the standings.\\\n**Note**: The players alternate who throws first in a leg has the mathematical \"head start\" to reach a finish before their opponent can take another turn. Players alternate who throws first with each leg.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# This function calculates the probability of the player \n# wins x time with given alpha, beta, and theta. \nProb.daltbbinom <- function(x, size, alpha, beta, theta){  \n  sapply(1:length(x), function(i){  # Ensure it works on a vector\n    xi <- x[i]  \n    si <- size[i]  \n    if(xi == 6){  # If the player win the match\n      # Calculate the probability and ensuring the last leg is win\n      (choose(si-1,5)/choose(si, xi)) * daltbbinom(xi, si, alpha, beta, theta) \n    } else {  # If the player lose the match\n      # Calculate the probability and ensuring the last leg is lose\n      (choose(si-1, xi)/choose(si, xi)) * daltbbinom(xi, si, alpha, beta, theta)  \n    }  \n  })  \n}\n\n\n\n# This function calculates the log likelihood of different parameters. \n# In order to make it easier for optimization, it returns the negative log likelihood.\nllProb.daltbbinom <- function(par, data){\n  alpha <- exp(par[1])\n  beta <- exp(par[2]) \n  theta <- exp(par[3])    \n  x <- data$Win\n  size <- data$Total\n  ll <- sum(log(Prob.daltbbinom(x,size,alpha, beta,theta)))\n  -ll\n}\n\n# Create a summary table for the result\nMLE.summary <- tibble(Name = names(player.turns),\n                      Alpha = NA,\n                      Beta = NA,\n                      Theta = NA,\n                      Mean = NA,\n                      sd = NA)\n\n# Repeat the process for each player\nfor(i in 1:nrow(MLE.summary)){\n  name <- MLE.summary$Name[i]\n  win.each <- Win.each(name) \n  mle <- optim(par = c(0,0,0), fn = llProb.daltbbinom, \n             data = win.each)\n  alpha <- exp(mle$par[1])\n  beta <- exp(mle$par[2])\n  MLE.summary$Alpha[i] <- alpha\n  MLE.summary$Beta[i] <- beta\n  MLE.summary$Theta[i] <- exp(mle$par[3])\n  MLE.summary$Mean[i] <- alpha / (alpha + beta)\n  MLE.summary$sd[i] <- ((alpha * beta)/((alpha + beta)^2 * (alpha + beta + 1))) ^ (1/2)\n}\n```\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell tbl-cap='Alpha, Beta and Theta for each player' tbl-align='center'}\n::: {.cell-output-display}\n\n\n|Name               | Alpha| Beta| Theta| Mean|   sd|\n|:------------------|-----:|----:|-----:|----:|----:|\n|Gerwyn Price       |  2.58| 3.98|  1.38| 0.39| 0.18|\n|Luke Humphries     |  3.48| 2.10|  1.36| 0.62| 0.19|\n|Luke Littler       |  3.15| 1.85|  1.50| 0.63| 0.20|\n|Michael Smith      |  2.67| 2.70|  1.41| 0.50| 0.20|\n|Michael van Gerwen |  3.46| 3.51|  1.34| 0.50| 0.18|\n|Nathan Aspinall    |  3.92| 3.66|  1.37| 0.52| 0.17|\n|Peter Wright       |  2.39| 9.88|  1.56| 0.19| 0.11|\n|Rob Cross          |  1.86| 2.34|  1.36| 0.44| 0.22|\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nBeta.plot <- function(i){\n  alpha <- MLE.summary$Alpha[i]\n  beta <- MLE.summary$Beta[i]\n  \n  ggdat <- tibble(x = seq(0, 1, 0.001)) |>\n  mutate(PDF = dbeta(x, alpha, beta))\n\n  PDF.plot <- ggplot(ggdat) +\n    geom_line(aes(x = x, y= PDF)) +\n    geom_hline(yintercept = 0) +\n    xlab(MLE.summary$Name[i]) +\n    ylab(\"Density\") +\n    theme_bw()\n  PDF.plot\n}\n\nBeta.plot(1) | Beta.plot(2) | Beta.plot(3)\n```\n\n::: {.cell-output-display}\n![](Lab10WriteUp_files/figure-pdf/figure5-1.pdf){fig-align='center' fig-pos='H'}\n:::\n\n```{.r .cell-code}\nBeta.plot(4) | Beta.plot(5) | Beta.plot(6)\n```\n\n::: {.cell-output-display}\n![](Lab10WriteUp_files/figure-pdf/figure5-2.pdf){fig-align='center' fig-pos='H'}\n:::\n\n```{.r .cell-code}\nBeta.plot(7) | Beta.plot(8)\n```\n\n::: {.cell-output-display}\n![](Lab10WriteUp_files/figure-pdf/figure5-3.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nThe data represent the maximum likelihood of alpha, beta, and theta for each player. Alpha and beta determines the probability of winning each match for the player if their results follows Altham's Multiplicative Beta Binomial Distribution. \n\n## Executive Summary\nSummarize the work you've done here to provide a brief (200-300 word) data-driven summary of the 2024 Premier League season using your work in Lab 10. Your summary should be professional, clear, and all claims should be corroborated with statistical support.\n\n**Solution**\n\nFor each player in the 2024 Premier League season data, I compute the number of matches and the total legs they played, and I calculate the proportion of matches and legs they won. The winning proportion of total matches range from 0.11 to 0.67. Luke Littler has the highest proportion, and Peter Wright has the lowest proportion. The winning proportion of total legs range from 0.37 to 0.56, and it contains less variation. Most players has a winning proportion aroung 0.5. Even though Peter Wright still has the lowest proportion, his leg winning proportion(0.37) is a lot higher than his match winning proportion (0.11).\n\nI use the number of legs won in each match to compute the maximium likelihood estimates for $p$ and $\\theta$ for each player, assuming the probability of the number of legs each player win in a match follows Altham's Multiplicative Binomial Distribution. The result demonstrates that the probability of each player winning a leg is mostly consistent with the result from winning proportion, as Luke Littler has the highest probability (0.59) and Peter Wright has the lowest probability (0.24). The higher the $\\theta$ is, the more likely for players to win matches with results 6-5 than 6-0. For most players, it is around 1.1, and Peter Wright has the highest $\\theta$ (1.30), and Rob Cross has the lowest $\\theta$ (1.04).\n\nI repeat the process but with assuming the probability follows Altham's multiplicative Beta Binomial Distribution. I estimated the parameter $\\alpha$, $\\beta$, and $\\theta$. Additionally, I calculate the mean and variance for the beta distribution for each player. Mean represent the average probability of player winning each leg in each matches, and the result is similar as Luke Littler has the highest mean and Peter Wright has the lowest value. Standard deviation for most player is around 0.2, except for Peter Wright (0.11), representing his probability of winning each leg has less variation.",
    "supporting": [
      "Lab10WriteUp_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}